version: '2'
services:
    ffbui-app:
        image: ffbui
        external_links:
            - ffbui-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - ffbui-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ffbui?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    ffbui-mysql:
        extends:
            file: mysql.yml
            service: ffbui-mysql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: ffbui-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
